name: Publish quarkus image
description: Setup Docker Hub & Publish Quarkus Image
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      env:
        USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Test secret access
      run: |
        echo "The secret is accessed but not shown for security reasons"
        if [[ -z "${{ env.USERNAME }}" ]]; then echo "DOCKER_HUB_USERNAME is empty"; fi
        if [[ -z "${{ env.PASSWORD }}" ]]; then echo "DOCKER_HUB_PASSWORD is empty"; fi
      shell: bash

    - name: Log into Docker Hub
      run: docker login -u ${{ env.USERNAME }} -p ${{ env.PASSWORD }}
      shell: bash

    - name: Build and push Docker image with Jib
      run: ./mvnw compile jib:build -Djib.to.image=docker.io/${{ github.repository }}:${{ github.sha }}
      shell: bash
